# Example configuration for Black.

# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 88
target-version = ['py38']

[tool.pyright]
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"

[tool.ruff]

[project]
name = "AWSnap"
description = "AWSnap is a tool for managing AWS SSO."
license = { text = "MIT" }
requires-python = ">=3.8"
authors = [
  { name = "Aaron West", email = "aphexlog@gmail.com" },
]

[tool.isort]
atomic = true
profile = "black"
line_length = 88
skip_gitignore = true
